image: node:alpine3.16

variables:
  DEPLOY_VERSION:
    value: "patch"
    options:
      - "major"
      - "minor"
      - "patch"
    description: "The deployment version. Set to 'patch' by default."
    
  DEPLOY_ENVIRONMENT:
    value: "staging"
    options:
      - "staging"
      - "prod"
    description: "The deployment environment. Set to 'staging' by default."

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - node_modules

test:
  stage: test
  script:
    - yarn test
  artifacts:
    paths:
      - node_modules/

deploy:
  stage: deploy
  script:
    - echo "This is a manual job which doesn't start automatically, Value of variables for DEPLOY_VERSION '$DEPLOY_VERSION' and DEPLOY_ENVIRONMENT '$DEPLOY_ENVIRONMENT'."
  when: manual


